#!/usr/bin/bash

query=$1
if [ -z $1 ]; then
	#echo -n "Search query: ";
	query=$(echo "" | rofi -dmenu -i -p "Search YT Video:")
fi

export query="$(sed 's/ /+/g' <<<$query)"
#echo "$query" > /home/gedas/tmp/yt/ytquery

#SEARCH="$( cat /home/gedas/tmp/yt/ytquery  )"

#echo ${SEARCH}
#mpv $(echo "https://youtu.be/$(curl https://www.googleapis.com/youtube/v3/search\?part\=snippet\&q\=${SEARCH}\&type\=video\&maxResults\=3330\&key\=$YT_API_KEY | jq -r '.items[] | "\(.snippet.title) \(.id.videoId)"' | rofi -dmenu -i -p 'Select Video:' -l 20  | awk '{print $NF}')")


#mpv https://youtube.com/$(curl -s "https://vid.puffyan.us/search?q=$query" | grep -Eo "watch\?v=.{11}" | head -n 1)

#curl -s "https://vid.puffyan.us/search?q=$query" | grep -Eo "<p dir="auto">.*</p>"

search=$(curl -s "https://vid.puffyan.us/search?q=$query" | grep -Eo "<p dir=\"auto\">.*</p>" | grep -Eo ">.*<" | sed 's/<//g' | sed 's/>//g' | rofi -dmenu | tr ' ' '+')
mpv https://youtube.com/$(curl -s "https://vid.puffyan.us/search?q=$search" | grep -Eo "watch\?v=.{11}" | head -n 1)
