#!/bin/bash

if ! tmux has-session -t main; then

tmux new -s main -d
tmux rename-window -t main terminal

tmux new-window -t main
tmux rename-window -t main irc
tmux send-keys -t main 'irssi' C-m


tmux new-window -t main
tmux rename-window -t main notes
tmux send-keys -t main 'cd ~/notes' C-m
tmux send-keys -t main 'vim ./' C-m


tmux new-window -t main
tmux rename-window -t main vim
tmux send-keys -t main 'vim' C-m
#tmux split-window -v -p 15 -t main

tmux select-window -t main:1
tmux attach -t main
fi
